red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

# Variables so its easy to make changes if I need to (it ended up being helpful)

all:
	

test:
	swipl -s list_operations_tests.pl -g run_tests,halt